### PR TITLE
Upgrade bibtex-ruby to 5.0.1

### PR DESCRIPTION
**Pull request by kohrVid**
The original [dependabot PR for upgrading bibtex-ruby](https://github.com/rayyansys/rayyan-formats-plugins/pull/25) breaks support for ruby v2.3. This PR downgrades the gem to 5.0.0, the latest version that supports 2.3.

### CODE REVIEW

**Comment by hammady** [comment]
What about 5.1.4? I don't see 2.3 support drop up to this version.

**Comment by kohrVid** [comment]
> What about 5.1.4? I don't see 2.3 support drop up to this version.

I'm not sure if it's in the official documation but whenever I run `bundle install` with versions later that 5.0.0, I get the following error:

    bibtex-ruby-5.1.4 requires ruby version >= 2.4.0, which is incompatible with the current version, ruby 2.3.0p0

However, if we still want to drop support for ruby versions <2.5, perhaps upgrading to 5.1.4 is ok?

**Comment by hammady** [comment]
They probably did not document the supported ruby versions in the [changelog](https://github.com/inukshuk/bibtex-ruby/blob/master/History.txt). Let's merge this now and have a follow-up issue to upgrade to the latest later.

**Review by hammady — APPROVED** [review]

**Comment by kohrVid** [comment]
I had to rebase this branch after some earlier PRs were merged and I noticed that some of the code I'd written broke specs in older ruby versions. To fix this, I've added a few more changes to this branch. Hopefully that should be ok.
Also noticed that it's safe to upgrade `bibtext-ruby` to v5.0.1 which doesn't appear in their official changelog

**Review by hammady — APPROVED** [review]

**Pull request merged**
